In [3]:
import numpy as np
import pandas as pd

In [33]:
df = pd.read_csv("healthcare_dataset.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [11]:
df.shape

(55500, 15)

In [13]:
df.dtypes

Name                      str
Age                     int64
Gender                    str
Blood Type                str
Medical Condition         str
Date of Admission         str
Doctor                    str
Hospital                  str
Insurance Provider        str
Billing Amount        float64
Room Number             int64
Admission Type            str
Discharge Date            str
Medication                str
Test Results              str
dtype: object

In [15]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [18]:
df['Medical Condition'].unique()

<StringArray>
['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension', 'Arthritis']
Length: 6, dtype: str

In [19]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [21]:
patients = df[['Name', 'Age','Medical Condition','Billing Amount']]

In [23]:
patients

                    Name  Age Medical Condition  Billing Amount
0          Bobby JacksOn   30            Cancer    18856.281306
1           LesLie TErRy   62           Obesity    33643.327287
2            DaNnY sMitH   76           Obesity    27955.096079
3           andrEw waTtS   28          Diabetes    37909.782410
4          adrIENNE bEll   43            Cancer    14238.317814
...                  ...  ...               ...             ...
55495  eLIZABeTH jaCkSOn   42            Asthma     2650.714952
55496         KYle pEREz   61           Obesity    31457.797307
55497       HEATher WaNG   38      Hypertension    27620.764717
55498     JENniFER JOneS   43         Arthritis    32451.092358
55499       jAMES GARCiA   53         Arthritis     4010.134172

[55500 rows x 4 columns]

In [32]:
df[(df['Medical Condition'] == "Diabetes") & (df['Age']> 50)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal
66,ChRiStOPhER gOnzAlez,59,Male,B+,Diabetes,2019-11-21,Patricia Dunn,Rhodes-Carey,Medicare,10107.187651,368,Emergency,2019-12-08,Penicillin,Abnormal
82,SeaN jenniNGs,80,Female,AB-,Diabetes,2023-11-12,James Tucker,Clark-Johnson,Blue Cross,20257.544283,255,Elective,2023-12-12,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55408,laura lOPEz,56,Female,O+,Diabetes,2022-02-27,Tyler Williamson,Smith-Butler,Blue Cross,5828.981010,421,Emergency,2022-03-23,Aspirin,Abnormal
55409,WEslEY BarkEr,58,Male,O+,Diabetes,2020-06-22,Jonathan Cabrera,Long LLC,Cigna,44241.630103,324,Urgent,2020-07-05,Ibuprofen,Normal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,UnitedHealthcare,5271.154491,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959.491185,462,Urgent,2019-12-06,Lipitor,Abnormal
55439,cHRiStINE MCCARty,75,Male,AB+,Diabetes,2024-04-28,Gregory Pineda,Wu-Stark,Aetna,23720.022368,313,Emergency,2024-05-19,Penicillin,Abnormal

In [30]:
df = df.drop_duplicates()

In [36]:
df = df[df["Billing Amount"] >= 0]
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [40]:
df['Name'] = df['Name'].str.title()

In [42]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

In [48]:
df['Length of Stay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
display(df.head())

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20

In [51]:
def get_age_group(age):
    if age <= 12:
        return "Child"
    elif age <=19:
        return "Teen"
    elif age <= 59:
        return "Adult"
    else: 
        return "Senior"

df['Age group'] = df['Age'].apply(get_age_group)

In [55]:
avg_billing = df['Billing Amount'].mean()
df['High Bill'] = df['Billing Amount'].apply(lambda x: "Yes" if x > avg_billing else "No")

In [57]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age group,High Bill
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,Adult,No
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Senior,Yes
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,Senior,Yes
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Adult,Yes
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult,No

In [60]:
top10 = df.sort_values(by = 'Billing Amount' , ascending=False).head(10)
top10[['Name','Medical Condition', 'Billing Amount']]

                   Name Medical Condition  Billing Amount
36349     Todd Carrillo      Hypertension    52764.276736
51313       Karen Kline            Cancer    52373.032374
34613       Karen Kline            Cancer    52373.032374
5735     David Sandoval      Hypertension    52271.663747
7088   Kathryn Gonzales          Diabetes    52211.852966
1574     Brett Marshall            Asthma    52181.837792
52826       Laurie Hood         Arthritis    52170.036854
6663        Laurie Hood         Arthritis    52170.036854
33117      Justin Clark            Cancer    52154.237722
34368      Scott Powell            Cancer    52102.240889

In [62]:
conditional_summary = df.groupby("Medical Condition").agg(
    average_billing = ("Billing Amount", "mean"),
    average_stay = ("Length of Stay","mean")
)

In [63]:
conditional_summary

                   average_billing  average_stay
Medical Condition
Arthritis             25528.123850     15.516941
Asthma                25686.666418     15.695429
Cancer                25214.907067     15.504670
Diabetes              25694.503197     15.422124
Hypertension          25556.094106     15.458803
Obesity               25860.321911     15.456253