In [6]:
import numpy as np
import pandas as pd

In [ ]:
label = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list, index=label)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### DataFrame

In [13]:
data = {
    "Name":['Sana','Amna','Hafsa','Rabia'],
    "Age": [29,30,21,32],
    "City":['Multan','Lahore','Karachi','Islamabad'],
    "Salary":[65000,80000,45000,60000]
}
df = pd.DataFrame(data)

In [15]:
df

    Name  Age       City  Salary
0   Sana   29     Multan   65000
1   Amna   30     Lahore   80000
2  Hafsa   21    Karachi   45000
3  Rabia   32  Islamabad   60000

In [17]:
data_list=[
    ['Sana',29	,'Multan',	65000],
    ['Amna',30	,'Lahore',80000],
    ['Hafsa',21	,'Karachi',45000],
    ['Rabia',32	,'Islamabad',60000]
]

df2 = pd.DataFrame(data_list)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=col)
df2

    Name  Age       City  Salary
0   Sana   29     Multan   65000
1   Amna   30     Lahore   80000
2  Hafsa   21    Karachi   45000
3  Rabia   32  Islamabad   60000

### Selection and Indexing of Column

In [20]:
df2[['Name','Age']]

    Name  Age
0   Sana   29
1   Amna   30
2  Hafsa   21
3  Rabia   32

### Create A new Column

In [23]:
df2['Designation'] = ['Engineer','Pilot','Doctor','Nurse']
df2

    Name  Age       City  Salary Designation
0   Sana   29     Multan   65000    Engineer
1   Amna   30     Lahore   80000       Pilot
2  Hafsa   21    Karachi   45000      Doctor
3  Rabia   32  Islamabad   60000       Nurse

### Remove a column

In [28]:
df2.drop('Designation', axis=1,inplace=True)

In [31]:
# Selecting a row
df2.loc[[0,1]]

   Name  Age    City  Salary
0  Sana   29  Multan   65000
1  Amna   30  Lahore   80000

In [33]:
df2.iloc[3]

Name          Rabia
Age              32
City      Islamabad
Salary        60000
Name: 3, dtype: object

In [36]:
df2.loc[[0,1]][['City','Salary']]

     City  Salary
0  Multan   65000
1  Lahore   80000

In [39]:
df2[df2['Age'] < 30]

    Name  Age     City  Salary
0   Sana   29   Multan   65000
2  Hafsa   21  Karachi   45000

In [41]:
df2[(df2['Age'] < 30) & (df2['City'] == 'Multan')]

   Name  Age    City  Salary
0  Sana   29  Multan   65000

### Find Missing Data

In [53]:
data = {
    'A':[1,2,np.nan , 4,5],
    'B': [np.nan, 2,3,4,5],
    'C': [1,2,3,np.nan,5],
    'D': [1,np.nan, np.nan,np.nan, 5]
}
df = pd.DataFrame(data)

In [54]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  5.0  5.0

In [50]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False  False  False

In [48]:
df.isna().sum()

A    1
B    1
C    1
D    3
dtype: int64

In [51]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [52]:
df.dropna()

     A    B    C    D
4  5.0  5.0  5.0  5.0

In [55]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  5.0  5.0

### Fill Missing Values

In [57]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  5.0  5.0

In [59]:
values = {'A':10,'B':20,'C':30,'D':40}
df.fillna(values)

      A     B     C     D
0   1.0  20.0   1.0   1.0
1   2.0   2.0   2.0  40.0
2  10.0   3.0   3.0  40.0
3   4.0   4.0  30.0  40.0
4   5.0   5.0   5.0   5.0

In [61]:
df.fillna(df.mean())

     A    B     C    D
0  1.0  3.5  1.00  1.0
1  2.0  2.0  2.00  3.0
2  3.0  3.0  3.00  3.0
3  4.0  4.0  2.75  3.0
4  5.0  5.0  5.00  5.0

### Merging and joining DataFrame

In [69]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['Sana','Amna','Nabiha','Hafsa','Rabia'],
    'department': ['HR','IT','IT','HR','Finance']
})


salaries  = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary': [80000,90000,60000,40000,50000],
    'bonous' : [2000,4000,6000,9000,3000]
})

In [70]:
employees

   employee_id    name department
0            1    Sana         HR
1            2    Amna         IT
2            3  Nabiha         IT
3            4   Hafsa         HR
4            5   Rabia    Finance

In [65]:
salaries

   employee_id  salary  bonous
0            1   80000    2000
1            2   90000    4000
2            3   60000    6000
3            6   40000    9000
4            7   50000    3000

In [73]:
pd.merge(employees,salaries, on='employee_id', how='inner')

   employee_id    name department  salary  bonous
0            1    Sana         HR   80000    2000
1            2    Amna         IT   90000    4000
2            3  Nabiha         IT   60000    6000

In [75]:
pd.merge(employees,salaries, on='employee_id', how='outer')

   employee_id    name department   salary  bonous
0            1    Sana         HR  80000.0  2000.0
1            2    Amna         IT  90000.0  4000.0
2            3  Nabiha         IT  60000.0  6000.0
3            4   Hafsa         HR      NaN     NaN
4            5   Rabia    Finance      NaN     NaN
5            6     NaN        NaN  40000.0  9000.0
6            7     NaN        NaN  50000.0  3000.0

In [76]:
pd.merge(employees,salaries, on='employee_id', how='left')

   employee_id    name department   salary  bonous
0            1    Sana         HR  80000.0  2000.0
1            2    Amna         IT  90000.0  4000.0
2            3  Nabiha         IT  60000.0  6000.0
3            4   Hafsa         HR      NaN     NaN
4            5   Rabia    Finance      NaN     NaN

In [78]:
pd.merge(employees,salaries, on='employee_id', how='right')

   employee_id    name department  salary  bonous
0            1    Sana         HR   80000    2000
1            2    Amna         IT   90000    4000
2            3  Nabiha         IT   60000    6000
3            6     NaN        NaN   40000    9000
4            7     NaN        NaN   50000    3000

### Concate the dataframe

In [80]:
d1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C' : ['C0','C1','C2']
})

d2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B3','B4'],
    'C': ['C3','C4','C5']
})

In [81]:
pd.concat([d1,d2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B3  C4
2  A5  B4  C5

In [83]:
pd.concat([d1,d2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B3  C4
2  A2  B2  C2  A5  B4  C5

In [86]:
# joing 2 data frame
j1 = pd.DataFrame({
    'name' : ['Sana','Amna','Hafsa']
}, index=[1,2,3])

j2 = pd.DataFrame({
    'score': [20,30,40]
}, index=[2,3,4])

In [88]:
j1.join(j2, how='outer')

    name  score
1   Sana    NaN
2   Amna   20.0
3  Hafsa   30.0
4    NaN   40.0

### Group By And Aggregation

In [91]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [92]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [96]:
cat = df.groupby('Category')
cat
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [101]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [104]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Aggregation

In [105]:
df['Sales'].mean()

np.float64(187.5)

In [107]:
df['Sales'].agg(['mean','max','min','count','sum','std','median'])

mean       187.500000
max        300.000000
min        100.000000
count        8.000000
sum       1500.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

### Pivot table

In [108]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    234     62   John  January      Q1
1  2023-01-02       B   West    184     24   Mary  January      Q1
2  2023-01-03       C  North    509     42    Bob  January      Q1
3  2023-01-04       D  South    143     33  Alice  January      Q1
4  2023-01-05       A   East    183     41   John  January      Q1
5  2023-01-06       B   West    956     42   Mary  January      Q1
6  2023-01-07       C  North    168     43    Bob  January      Q1
7  2023-01-08       D  South    326     46  Alice  January      Q1
8  2023-01-09       A   East    258     80   John  January      Q1
9  2023-01-10       B   West    424     76   Mary  January      Q1
10 2023-01-11       C  North    115     73    Bob  January      Q1
11 2023-01-12       D  South    605     75  Alice  January      Q1
12 2023-01-13       A   East    663     26   John  January      Q1
13 2023-01-14       B   West    291     79   Mary  January      Q1
14 2023-01-15       C  North    306     86    Bob  January      Q1
15 2023-01-16       D  South    509     10  Alice  January      Q1
16 2023-01-17       A   East    882     16   John  January      Q1
17 2023-01-18       B   West    914     37   Mary  January      Q1
18 2023-01-19       C  North    488     32    Bob  January      Q1
19 2023-01-20       D  South    571     31  Alice  January      Q1

In [110]:
pivot1 = pd.pivot_table(df, values='Sales',index='Region', columns='Product',aggfunc='median')
pivot1

Product      A      B      C      D
Region
East     258.0    NaN    NaN    NaN
North      NaN    NaN  306.0    NaN
South      NaN    NaN    NaN  509.0
West       NaN  424.0    NaN    NaN

In [111]:
pivot2 = pd.pivot_table(df, values=['Sales','Units'],index='Region', columns='Product',aggfunc='median')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     258.0    NaN    NaN    NaN  41.0   NaN   NaN   NaN
North      NaN    NaN  306.0    NaN   NaN   NaN  43.0   NaN
South      NaN    NaN    NaN  509.0   NaN   NaN   NaN  33.0
West       NaN  424.0    NaN    NaN   NaN  42.0   NaN   NaN

### Cross Tab

In [114]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operation

In [116]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [117]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [119]:
df1.shape

(5, 3)

In [124]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [121]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [123]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [125]:
def square(x):
    return x**2

In [130]:
df1['D'] = df1['B'].apply(square)

In [132]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [133]:
df1['D'] = df1['B'].apply(lambda x : x**2)