In [1]:
import numpy as np
import pandas as pd

In [2]:
a = [1,2,3,4,5]

In [3]:
print(pd.Series(a))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
d = {"Aman":20,"Sana":60,"Saima":80}
print(pd.Series(d))
print(pd.DataFrame([d]))

Aman     20
Sana     60
Saima    80
dtype: int64
   Aman  Sana  Saima
0    20    60     80

In [5]:
pd.DataFrame({
    "name":["Sana","Amna"],
    "salary": [40000,60000]}
)

   name  salary
0  Sana   40000
1  Amna   60000

In [6]:
df = pd.read_csv("employees_100.csv")

In [7]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [8]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [9]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
41,135,Meera Desai,Marketing,Kolkata,28.0,59186,4,6,8,2023-07-10

In [10]:
df.shape

(100, 10)

In [11]:
df.dtypes

employee_id             int64
name                      str
department                str
city                      str
age                   float64
salary                    str
experience              int64
performance_score       int64
projects_completed      int64
joining_date              str
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [13]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: str

In [14]:
df[['salary','name']].head()

  salary            name
0  70719    Swati Kapoor
1  77058  Kavya Malhotra
2  69911    Manish Desai
3  69993        Neha Das
4  88216       Isha Nair

In [15]:
df.loc[[146,145]]

KeyError: 'None of [RangeIndex(start=146, stop=144, step=-1)] are in the [index]'

In [ ]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [ ]:
df[ df["age"] > 40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
df[((df["department"] == "Finance") | (df["department"] == "Finance" )) & (df['age']>30) & (df['experience'] > 5)]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
58,137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
82,138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

In [ ]:
df[df["department"].isin(["Engineering", "Data Science"])]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
8,111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
15,105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
19,132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765,0,2,4,2020-04-12
22,127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
25,116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
31,148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
34,194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
42,108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
59,190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
63,144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
66,147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
92,187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05

In [ ]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [ ]:
# Data Cleaning
df.dropna(subset = ["city", "age"])

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [ ]:
df['age'].fillna(df['age'].mean(), inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_12936\1503503937.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'].fillna(df['age'].mean(), inplace=True)

0     38.000000
1     30.861702
2     23.000000
3     28.000000
4     32.000000
        ...
95    22.000000
96    22.000000
97    43.000000
98    23.000000
99    44.000000
Name: age, Length: 100, dtype: float64

In [ ]:
df['joining_date'] = pd.to_datetime(df['joining_date'])

In [ ]:
df["annual_salary"] = df["salary"] * 12

In [ ]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.0,7071970719707197071970719707197071970719707197...,5,5,6,2021-07-02,7071970719707197071970719707197071970719707197...
1,154,Kavya Malhotra,engineering,Mumbai,NaN,7705877058770587705877058770587705877058770587...,1,8,8,2024-02-05,7705877058770587705877058770587705877058770587...
2,171,Manish Desai,Data Science,Hyderabad,23.0,6991169911699116991169911699116991169911699116...,0,6,18,2019-04-24,6991169911699116991169911699116991169911699116...
3,146,Neha Das,Engineering,Pune,28.0,6999369993699936999369993699936999369993699936...,3,8,1,2022-12-13,6999369993699936999369993699936999369993699936...
4,145,Isha Nair,Data Science,NaN,32.0,8821688216882168821688216882168821688216882168...,8,8,14,2019-11-25,8821688216882168821688216882168821688216882168...

In [ ]:
def catagorize(num):
    if num > 5:
        return "Experienced"
    elif num <= 5:
        return " Learner"

In [ ]:
df["experience_status"]  = df["experience"].apply(catagorize)
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.0,7071970719707197071970719707197071970719707197...,5,5,6,2021-07-02,7071970719707197071970719707197071970719707197...,Learner
1,154,Kavya Malhotra,engineering,Mumbai,NaN,7705877058770587705877058770587705877058770587...,1,8,8,2024-02-05,7705877058770587705877058770587705877058770587...,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.0,6991169911699116991169911699116991169911699116...,0,6,18,2019-04-24,6991169911699116991169911699116991169911699116...,Learner
3,146,Neha Das,Engineering,Pune,28.0,6999369993699936999369993699936999369993699936...,3,8,1,2022-12-13,6999369993699936999369993699936999369993699936...,Learner
4,145,Isha Nair,Data Science,NaN,32.0,8821688216882168821688216882168821688216882168...,8,8,14,2019-11-25,8821688216882168821688216882168821688216882168...,Experienced

In [18]:
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

df["salary_level"] = df["salary"].apply(
    lambda salary: "High" if salary > 70000 else "Normal"
)

In [29]:
department_code = {"Engineering": "ENG","Marketing": "MKT", "Finance": "FIN","Data Science":"DS"}
df["department_code"] = df["department"].map(department_code)
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_level,department_code
0,184,Swati Kapoor,Data Science,Kolkata,38,70719.0,5,5,6,2021-07-02,High,DS
1,154,Kavya Malhotra,engineering,Mumbai,30,77058.0,1,8,8,2024-02-05,High,NaN
2,171,Manish Desai,Data Science,Hyderabad,23,69911.0,0,6,18,2019-04-24,Normal,DS
3,146,Neha Das,Engineering,Pune,28,69993.0,3,8,1,2022-12-13,Normal,ENG
4,145,Isha Nair,Data Science,NaN,32,88216.0,8,8,14,2019-11-25,High,DS

In [28]:
df["age"] = df["age"].fillna(df["age"].mean()).astype(int)