In [6]:
import numpy as np
import pandas as pd

In [ ]:
label = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list, index=label)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### DataFrame

In [13]:
data = {
    "Name":['Sana','Amna','Hafsa','Rabia'],
    "Age": [29,30,21,32],
    "City":['Multan','Lahore','Karachi','Islamabad'],
    "Salary":[65000,80000,45000,60000]
}
df = pd.DataFrame(data)

In [15]:
df

    Name  Age       City  Salary
0   Sana   29     Multan   65000
1   Amna   30     Lahore   80000
2  Hafsa   21    Karachi   45000
3  Rabia   32  Islamabad   60000

In [17]:
data_list=[
    ['Sana',29	,'Multan',	65000],
    ['Amna',30	,'Lahore',80000],
    ['Hafsa',21	,'Karachi',45000],
    ['Rabia',32	,'Islamabad',60000]
]

df2 = pd.DataFrame(data_list)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=col)
df2

    Name  Age       City  Salary
0   Sana   29     Multan   65000
1   Amna   30     Lahore   80000
2  Hafsa   21    Karachi   45000
3  Rabia   32  Islamabad   60000

### Selection and Indexing of Column

In [20]:
df2[['Name','Age']]

    Name  Age
0   Sana   29
1   Amna   30
2  Hafsa   21
3  Rabia   32

### Create A new Column

In [23]:
df2['Designation'] = ['Engineer','Pilot','Doctor','Nurse']
df2

    Name  Age       City  Salary Designation
0   Sana   29     Multan   65000    Engineer
1   Amna   30     Lahore   80000       Pilot
2  Hafsa   21    Karachi   45000      Doctor
3  Rabia   32  Islamabad   60000       Nurse

### Remove a column

In [28]:
df2.drop('Designation', axis=1,inplace=True)

In [31]:
# Selecting a row
df2.loc[[0,1]]

   Name  Age    City  Salary
0  Sana   29  Multan   65000
1  Amna   30  Lahore   80000

In [33]:
df2.iloc[3]

Name          Rabia
Age              32
City      Islamabad
Salary        60000
Name: 3, dtype: object

In [36]:
df2.loc[[0,1]][['City','Salary']]

     City  Salary
0  Multan   65000
1  Lahore   80000

In [39]:
df2[df2['Age'] < 30]

    Name  Age     City  Salary
0   Sana   29   Multan   65000
2  Hafsa   21  Karachi   45000

In [41]:
df2[(df2['Age'] < 30) & (df2['City'] == 'Multan')]

   Name  Age    City  Salary
0  Sana   29  Multan   65000

### Find Missing Data

In [53]:
data = {
    'A':[1,2,np.nan , 4,5],
    'B': [np.nan, 2,3,4,5],
    'C': [1,2,3,np.nan,5],
    'D': [1,np.nan, np.nan,np.nan, 5]
}
df = pd.DataFrame(data)

In [54]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  5.0  5.0

In [50]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False  False  False

In [48]:
df.isna().sum()

A    1
B    1
C    1
D    3
dtype: int64

In [51]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [52]:
df.dropna()

     A    B    C    D
4  5.0  5.0  5.0  5.0

In [55]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  5.0  5.0

### Fill Missing Values

In [57]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  5.0  5.0

In [59]:
values = {'A':10,'B':20,'C':30,'D':40}
df.fillna(values)

      A     B     C     D
0   1.0  20.0   1.0   1.0
1   2.0   2.0   2.0  40.0
2  10.0   3.0   3.0  40.0
3   4.0   4.0  30.0  40.0
4   5.0   5.0   5.0   5.0

In [61]:
df.fillna(df.mean())

     A    B     C    D
0  1.0  3.5  1.00  1.0
1  2.0  2.0  2.00  3.0
2  3.0  3.0  3.00  3.0
3  4.0  4.0  2.75  3.0
4  5.0  5.0  5.00  5.0

### Merging and joining DataFrame

In [69]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['Sana','Amna','Nabiha','Hafsa','Rabia'],
    'department': ['HR','IT','IT','HR','Finance']
})


salaries  = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary': [80000,90000,60000,40000,50000],
    'bonous' : [2000,4000,6000,9000,3000]
})

In [70]:
employees

   employee_id    name department
0            1    Sana         HR
1            2    Amna         IT
2            3  Nabiha         IT
3            4   Hafsa         HR
4            5   Rabia    Finance

In [65]:
salaries

   employee_id  salary  bonous
0            1   80000    2000
1            2   90000    4000
2            3   60000    6000
3            6   40000    9000
4            7   50000    3000

In [71]:
pd.merge(employees,salaries, on='employee_id')

   employee_id    name department  salary  bonous
0            1    Sana         HR   80000    2000
1            2    Amna         IT   90000    4000
2            3  Nabiha         IT   60000    6000