In [18]:
import numpy as np
import pandas as pd

In [19]:
a = [1,2,3,4,5]

In [21]:
print(pd.Series(a))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
d = {"Aman":20,"Sana":60,"Saima":80}
print(pd.Series(d))
print(pd.DataFrame([d]))

Aman     20
Sana     60
Saima    80
dtype: int64
   Aman  Sana  Saima
0    20    60     80

In [27]:
pd.DataFrame({
    "name":["Sana","Amna"],
    "salary": [40000,60000]}
)

   name  salary
0  Sana   40000
1  Amna   60000

In [30]:
df = pd.read_csv("employees_100.csv")

In [33]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [35]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [37]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22

In [40]:
df.shape

(100, 10)

In [42]:
df.dtypes

employee_id             int64
name                      str
department                str
city                      str
age                   float64
salary                    str
experience              int64
performance_score       int64
projects_completed      int64
joining_date              str
dtype: object

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [59]:
df['salary']

employee_id
184    70719
154    77058
171    69911
146    69993
145    88216
       ...
161    55740
172    52250
115      NaN
193    56821
152    69499
Name: salary, Length: 100, dtype: str

In [58]:
df[['salary','name']].head()

            salary            name
employee_id
184          70719    Swati Kapoor
154          77058  Kavya Malhotra
171          69911    Manish Desai
146          69993        Neha Das
145          88216       Isha Nair

In [70]:
df.loc[[146,145]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [73]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [78]:
df[ df["age"] > 40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25